%% ########################################################
%% ======================================================
\begin{center}

%{\sf{\huge \sphinxDocumentTitle}} \\[5mm]
\begin{tabularx}{\textwidth}{ |L|L|L|L|L|L| }
    \hline
    \bf{Wydział:} \sphinxDocumentFaculty &
    \multicolumn{2}{|p{2\dimexpr \textwidth /6 - 2\tabcolsep}|}{\bf{Autor/Autorzy:} \sphinxDocumentAuthor} &
    \bf{Rok:} \sphinxDocumentYear &
    \bf{Grupa:} \sphinxDocumentGroupID &
    \bf{Zespół:} \sphinxDocumentTeam \\
    \hline

    \multicolumn{2}{|p{2\dimexpr \textwidth/6 - 2\tabcolsep}|}{\bf{\sphinxSubjectName}} &
    \multicolumn{2}{p{2\dimexpr \textwidth/6 - 2\tabcolsep}|}{\sphinxDocumentTitle} &
    \multicolumn{2}{p{2\dimexpr \textwidth/6 - 2\tabcolsep}|}{\bf{Ćwiczenie nr:} \sphinxDocumentNumber} \\
    \hline

    \bf{Data wykonania:} \sphinxDocumentTaskDate &
    \bf{Data oddania:} \sphinxDocumentCreationDate &
    \bf{Zwrot do popr.:} &
    \bf{Data oddania:} \sphinxDocumentCorrectionDate &
    \bf{Data zaliczenia:} &
    \bf{Ocena:} \\
    \hline
\end{tabularx}
\end{center}

%%\begin{center}
%%{\sf \sphinxDocumentTownAndYear}
%%\end{center}

%% ########################################################
%% ########################################################
%%\end{document}

